<?php
/*---------------------------------------------------------------------+
| PHPince Website
| Copyright (c) 2011 - 2013 Dominik Hulla
| Web: http://phpince.com
| Author: Dominik Hulla / dh@bladrion.com
| Developer: Bladrion Technologies (http://bladrion.com)
+----------------------------------------------------------------------+
| This program is free software: you can redistribute it and/or modify
| it under the terms of the GNU General Public License as published by
| the Free Software Foundation, either version 3 of the License, or
| (at your option) any later version.
| 
| This program is distributed in the hope that it will be useful,
| but WITHOUT ANY WARRANTY; without even the implied warranty of
| MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
| GNU General Public License for more details.
| Removal of this copyright header is strictly prohibited 
| without written permission from the original author(s).
| 
| You should have received a copy of the GNU General Public License
| along with this program.  If not, see <http://www.gnu.org/licenses/>.
+----------------------------------------------------------------------*/
header('Content-Type: text/html; charset=utf-8');
$PHPINCE_LANG = array(
	"English" => array(
	),
	"Slovensky" => array(
	//Webadmin
		0 => 'Webový panel',
		1 => 'Funguje na',
		2 => 'Jednoduchý redakčný systém',
		3 => 'Web-stránka',
		4 => 'Administrácia',
		5 => 'Nastavenia',
		6 => 'Odhlásiť',
		7 => 'Navigácia',
		8 => 'Môj účet',
		9 => 'Uložiť',
		10 => 'Obnoviť',
		11 => 'Áno',
		12 => 'Nie',
		13 => 'Aktualizácia web-stránky prebehne za', //?? seconds
		14 => 'Články',
		15 => 'Stránky',
		16 => 'Súbory',
		17 => 'Používatelia',
		18 => 'Navigácia',
		19 => 'Moduly',
		20 => 'Rozloženie',
		21 => 'Zakázať prístup',
		22 => 'Štatistiky',
		23 => 'Skripty',
		24 => 'Môj profil',
		25 => 'Zmeniť heslo',
		26 => 'Oprávnenia',
		27 => 'Aktualizovať teraz na',
		28 => 'Aktualizoval systém',
		29 => 'sk',
	//Login system
		100 => 'Prihlásenie',
		101 => 'Prosím, vyplňte účet a heslo.',
		102 => 'Prihlásenie',
		103 => 'Účet alebo heslo je nesprávne',
		104 => 'Prihlásiť',
		105 => 'Účet',
		106 => 'Heslo',
		107 => 'Vytvoriť nový účet',
		108 => 'Zabudnuté heslo',
		109 => 'Registrácia',
		110 => 'E-Mail',
		111 => 'Opíšte len modré číslice z obrázku',
		112 => 'Vytvoriť účet',
		113 => 'Registráciou súhlasíte, že môžme zapisovať vašu IP adresu.',
		114 => 'Prosím, vyplňte všetky polia',
		115 => 'Vytvorenie účtu prebehlo úspešne.<br>Prebieha automatické presmerovanie ...',
		116 => 'Účet ktorý sa pokúšate vytvoriť už existuje alebo zadaná E-Mailová adresa už je použitá.',
		117 => 'Zadávajte len povolené znaky.',
		118 => 'Opísali ste zle obrázok.',
		119 => 'Zadávajte len znaky a-z, A-Z, 0-9',
		120 => 'Nové heslo',
		121 => 'Zopakujte nové heslo',
		123 => 'Zadaný účet neexistuje',
		124 => 'Obnoviť heslo',
		125 => 'Heslá sa nezhodujú',
		126 => 'Dobrý deň', //{Username},
		127 => 'Váš overovací kľúč k obnoveniu hesla je:',
		128 => 'Svoje heslo si môžte uplatniť tu:',
		129 => 'Obnova hesla prebehla úspešne, na E-Mail bol odoslaný aktivačný kľúč:',
		130 => 'Kľúč',
		131 => 'Zadaný aktivačný kľúč neexistuje alebo uplynula jeho platnosť.',
		132 => 'Obnova hesla prebehla úspešne.<br>Prebieha automatické presmerovanie ...',
		133 => 'Odhlásenie',
	//Error pages
		200 => 'Prístup zablokovaný',
		201 => 'Vaša IP adresa bola zablokovaná, viac informácií čítajte tu:',
		202 => 'Vaša IP adresa bola zablokovaná na {BAN_TIME} minút. Dôvodom tohto zablokovania je veľký počet ne uhádnutia hesla k účtu.',
		203 => 'Na web-stránke sa pracuje',
		204 => 'Ospravedlňujeme sa, ale na webovej stránke sa pracuje. Navštívte prosím túto stránku neskôr.',
	//Webadmin: Home
		300 => 'Administrácia',
		301 => 'Systémové informácie',
		302 => 'Názov stránky',
		303 => 'Verzia PHP',
		304 => 'Verzia MySQL',
		305 => 'Verzia systému',
		306 => 'Verzia jadra',
		307 => 'Štatistika web-stránky',
		308 => 'Počet článkov',
		309 => 'Počet stránok',
		310 => 'Počet užívateľov',
		311 => 'Počet blokovaných IP',
		312 => 'Veľkosť databázy',
		313 => 'Prístup na môj účet',
		314 => 'Čas',
		315 => 'IP adresa',
		316 => 'Akcia',
		317 => 'Systémový záznam',
		318 => 'Google PageRank',
		319 => 'Návštevnosť webu dnes',
		320 => 'Účet',
	//Webadmin: Settings
		500 => 'Systémové nastavenia',
		501 => 'Jazyk systému',
		502 => 'Znaková sada web stránky',
		503 => 'Verzia HTML aktívneho štýlu',
		504 => 'Štýl web stránky',
		505 => 'Wysiwyg editor',
		506 => 'Formát času',
		507 => 'hodín',
		508 => 'Povoliť registráciu nových užívateľov',
		509 => 'Overovať aktuálnu verziu',
		510 => 'Povoliť doplnok Bladrion - IntelDoc',
		511 => 'Povoliť doplnok STOPspam',
		512 => 'Optimalizácia pre vyhľadávače',
		513 => 'Názov web stránky',
		514 => 'Informácie o web stránke',
		515 => 'Kľúčové slová',
		516 => 'Slová oddeľujte čiarkou',
		517 => 'Indexovať web stránku',
		518 => 'Prosím, vyplňte všetky polia',
		519 => 'Vyplňujte len povolené znaky',
		520 => 'Nastavenia boli úspešne upravené',
		521 => 'Upravil nastavenia',
		522 => 'Bezpečnosť',
		523 => 'Blokovať prihlásenie pri nesprávnom hesle',
		524 => 'Čas blokovania prístupu',
		525 => 'zlé prihlásenie',
		526 => 'minút',
		527 => 'Uzamknúť web-stránku pre verejnosť',
	//Webadmin: Change password
		600 => 'Zmena hesla',
		601 => 'Staré heslo',
		602 => 'Nové heslo',
		603 => 'Povolené znaky: a-z, A-Z, 0-9',
		604 => 'Zopakujte nové heslo',
		605 => 'Vyplňte všetky heslá',
		606 => 'Nové heslo sa nezhoduje',
		607 => 'Staré heslo je nesprávne',
		608 => 'Heslo bolo úspešne zmenené',
	//Webadmin: Account
		700 => 'Môj profil',
		701 => 'E-Mail',
		702 => 'Registrovaný od',
		703 => 'Úroveň účtu',
		704 => 'Zmeniť E-Mail',
		705 => 'Zadajte platný E-Mail',
		706 => 'E-Mail bol úspešne aktualizovaný',
	//Webadmin: Files
		800 => 'Súbory',
		801 => 'Nahrať nové súbory',
		802 => 'Názov súboru',
		803 => 'Veľkosť',
		804 => 'Nahranie prebehol úspešne',
		805 => 'Nebol nájdený žiaden súbor.',
		806 => 'Nahral nový súbor:',
		807 => 'Zmazal súbor:',
		808 => 'Upravil súbor:',
	//Webadmin: Navigation
		900 => 'Navigácia',
		901 => 'Vytvoriť novú navigáciu',
		902 => 'Navigácia číslo:',
		903 => 'Pridať nový odkaz',
		904 => 'Nový odkaz',
		905 => 'Názov odkazu',
		906 => 'Adresa odkazu',
		907 => 'Cieľ odkazu',
		908 => 'Názov odkazu alebo adresa odkazu nie je vyplnená',
		909 => 'Úprava odkazu',
		910 => 'Upravil poradie navigácie',
		911 => 'Zmazal odkaz',
		912 => 'Zmazal navigáciu',
		913 => 'Pridal novú navigáciu',
		914 => 'Upravil odkaz',
		915 => 'Pridal nový odkaz',
		916 => 'Otvoriť v aktívnom okne',
		917 => 'Otvoriť v novom okne alebo karte',
	//Webadmin: Scripts
		1000 => 'Skripty',
		1001 => 'Názov skriptu',
		1002 => 'Spustil script:',
	//Webadmin: Perms
		1100 => 'Oprávnenia',
		1101 => 'Upravil oprávnenia',
		1102 => 'a vyššia úroveň',
		1103 => 'Oprávnenia zmenené',
	//Webadmin: Ban
		1200 => 'Zakázanie prístupu',
		1201 => 'IP adresa',
		1202 => 'Platné do',
		1203 => 'Typ zablokovania',
		1204 => 'Autor',
		1205 => 'Správa',
		1206 => 'Status',
		1207 => 'Aktívny',
		1208 => 'Neaktívny',
		1209 => 'Navždy',
		1210 => 'Prihlásenie',
		1211 => 'Celý web',
		1212 => 'Odblokoval IP',
		1213 => 'Nebol udelený žiaden zákaz.',
		1214 => 'Nové zablokovanie',
		1215 => 'Počet dní',
		1216 => 'Zablokoval IP',
		1217 => 'Vyplňte IP adresu',
	//Webadmin: Users
		1300 => 'Používatelia',
		1301 => 'Názov účtu',
		1302 => 'Posledné prihlásenie',
		1303 => 'Oprávnenia',
		1304 => 'Registrovaný od',
		1305 => 'Posledná IP',
		1306 => 'Vyplňte polia v správnom formáte',
		1307 => 'Upravil užívateľa',
		1308 => 'Zmenil heslo užívateľovi',
	//Webadmin: Pages
		1400 => 'Stránky',
		1401 => 'Vytvoriť novú',
		1402 => 'Názov stránky',
		1403 => 'Posledná úprava',
		1404 => 'Autor',
		1410 => 'Neboli vytvorené žiadne stránky.',
		1405 => 'Vyplňte názov stránky a text',
		1406 => 'Vytvoril stránku:',
		1407 => 'Upravil stránku:',
		1408 => 'Stránka úspešne upravená, <a href="/panel/pages">späť na stránky</a>',
		1409 => 'Zmazal stránku:',
	//Webadmin: News
		1500 => 'Články',
		1501 => 'Vytvoriť nový',
		1502 => 'Názov článku',
		1503 => 'Posledná úprava',
		1504 => 'Autor',
		1505 => 'Vyplňte názov článku a text',
		1506 => 'Vytvoril článok:',
		1507 => 'Upravil článok:',
		1508 => 'Článok úspešne upravený, <a href="/panel/news">späť na články</a>',
		1509 => 'Zmazal článok:',
		1510 => 'Neboli vytvorené žiadne články.',
		1511 => 'Nezaradené',
		1512 => 'Kategória',
		1513 => 'Kategórie',
		1514 => 'Vytvoriť novú',
		1515 => 'Názov kategórie',
		1516 => 'Zmazal kategóriu:',
		1517 => 'Vyplňte názov',
		1518 => 'Úprava kategórie',
		1519 => 'Kategória úspešne upravená, <a href="/panel/news">späť na články</a>',
		1520 => 'Upravil kategóriu:',
		1521 => 'Pridal novú kategóriu:',
		1522 => 'Neboli vytvorené žiadne kategórie',
	//Webadmin: Apps
		1600 => 'Moduly',
		1601 => 'Priečinok modulu',
		1602 => 'Odinštaloval modul:',
		1603 => 'Nainštaloval modul:',
	//Webadmin: Formating
		1700 => 'Rozloženie',
		1701 => 'Rozloženie upravené',
		1702 => 'Upravil rozloženie',
		1703 => 'Pri úprave hore uvedeného kódu potrebujete znalosť PHPince značiek. Pre viac info si prezrite <a target="_blank" href="http://phpince.com/page/21">tutorial</a>.',
	//Webadmin: Stats
		1800 => 'Štatistiky',
		1801 => 'Návštevnosť tento deň',
		1802 => 'Návštevnosť tento mesiac',
		1803 => 'Návštevnosť tento rok',
		1804 => 'Návštevnosť celkovo',
		1805 => 'Návštevnosť web-stránky',
		1806 => 'Celkový počet štátov',
		1807 => 'Stránky odkazujúce na môj web',
		1808 => 'Počet odkazov na môj web',
		1809 => 'Počet návštev robotov',
		1810 => 'Názov',
		1811 => 'Počet',
		1812 => 'Operačný systém',
		1813 => 'Internetový prehliadač',
		1814 => 'Štatistika lokácie',
		1815 => 'Stránky odkazujúce na môj web',
		1816 => 'Štatistika robotov',
	//Ranks
		400 => 'Úroveň 0',
		401 => 'Úroveň 1',
		402 => 'Úroveň 2',
		403 => 'Úroveň 3',
		404 => 'Úroveň 4',
		405 => 'Úroveň 5',
		406 => 'Úroveň 6',
		407 => 'Úroveň 7',
		408 => 'Úroveň 8',
		409 => 'Úroveň 9',
		410 => 'Úroveň 10',
	//Perms
		2002 => 'Zobrazovať systémový log',
		2003 => 'Zobrazovať systémové informácie',
		2004 => 'Prístup k položke "Nastavenia"',
		2005 => 'Prístup k položke "Súbory"',
		2006 => 'Prístup k položke "Navigácia"',
		2007 => 'Prístup na web v construction modu',
		2008 => 'Prístup k položke "Skripty"',
		2009 => 'Prístup k položke "Zakázať prístup"',
		2010 => 'Prístup k položke "Oprávnenia"',
		2011 => 'Prístup k položke "Používatelia"',
		2012 => 'Možnosť spustiť systémovú aktualizáciu',
		2013 => 'Prístup k položke "Stránky"',
		2014 => 'Stránky: Možnosť upravovať všetky stránky',
		2015 => 'Prístup k položke "Články"',
		2016 => 'Články: Možnosť upravovať všetky články',
		2017 => 'Články: Možnosť pridávať/upravovať kategórie',
		2018 => 'Prístup k položke "Moduly"',
		2019 => 'Prístup k položke "Rozloženie"',
		2020 => 'Prístup k položke "Štatistiky"',
	//Formatings
		3001 => 'Zobrazenie článkov',
		3002 => 'Zobrazenie jedného článku',
		3003 => 'Správa ak článok neexistuje',
		3004 => 'Správa ak nie je vypísaný žiaden článok',
		3005 => 'Zobrazenie stránky',
		3006 => 'Správa ak stránka neexistuje',
		3007 => 'Správa ak modul neexistuje',
	)
);
?>